from PIL import Image
import math

# Some constant definitions for verbally accessing arrays.
FIRST = 0
SECOND = 1


class Agent:
    SKIP = -1
    PROBLEM_FIGURE_NAMES = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']
    SOLUTION_FIGURE_NAMES = ['1', '2', '3', '4', '5', '6']

    @staticmethod
    def pixel_match_percentage(image1_pixels, image2_pixels):
        """Compares two image's pixels and returns the percentage that those
        two pixel lists match.

        Args:
            image1_pixels (list): A list of pixels in an image.
            image2_pixels (list): A list of pixels in an image.

        Return:
            (float): Percentage the two pixel lists match.
        """

        match, total = 0, 0
        for i in range(len(image1_pixels)):
            if image1_pixels[i] == image2_pixels[i]:
                match += 1
                total += 1
            else:
                total += 1
        return float(match) / float(total)

    @staticmethod
    def generate_problem_images(problem):
        """Generate images for each solution and problem figure.

        Args:
            problem (RavensProblem): A object containing all information about
                the RPM problem being solved.

            Returns:
                (dict): Dictionary of problem figures.
                (dict): Dictionary of solution figures.
                    Both dictionary returns respond with a dictionary object
                    in the form of:
                        {
                            'image':  # The figure image as a PIL image.
                            'pixels':  # A list of pixels in the image.
                        }
        """

        problem_figures = {}
        solution_figures = {}
        for figure in problem.figures.itervalues():
            figure_image = Image.open(figure.visualFilename)
            image_pixels = list(figure_image.getdata())
            image_details = dict(image=figure_image, pixels=image_pixels)
            if figure.name in Agent.PROBLEM_FIGURE_NAMES:
                problem_figures[figure.name] = image_details
            elif figure.name in Agent.SOLUTION_FIGURE_NAMES:
                solution_figures[figure.name] = image_details
        return problem_figures, solution_figures

    def __init__(self):
        pass

    def Solve(self, problem):
        """The main agent method called for each problem.

        Args:
            problem (RavensProblem): A object containing all information about
                the RPM problem being solved.

        Return:
            (int): The solution generated by the agent.
        """

        if not problem.hasVisual:
            return Agent.SKIP
        if problem.problemType != '2x2':
            return Agent.SKIP

        if problem.problemType == '2x2':
            solution_map = {'AB': 'C',
                            'AC': 'B'}

        problem_figures = {}
        solution_figures = {}

        problem_figures, solution_figures = \
            Agent.generate_problem_images(problem)

        closest_match = dict(name='-1', difference=1.00)

        # Compare the pixel ratio from A->B and compare C with each solution
        for from_pair, apply_to in solution_map.iteritems():
            image1_pixels = problem_figures[from_pair[FIRST]]['pixels']
            image2_pixels = problem_figures[from_pair[SECOND]]['pixels']
            match = Agent.pixel_match_percentage(image1_pixels, image2_pixels)
            solution_matches = {}
            for solution_figure_name, solution_figure in \
                    solution_figures.iteritems():
                apply_to_image_pixels = problem_figures[apply_to]['pixels']
                solution_matches[solution_figure_name] = \
                    Agent.pixel_match_percentage(apply_to_image_pixels,
                                                 solution_figure['pixels'])

            for solution_figure_name, solution_match in \
                    solution_matches.iteritems():
                if solution_match == match:
                    return int(solution_figure_name)

            for solution_figure_name, solution_match in \
                    solution_matches.iteritems():
                match_difference = math.fabs(solution_match - match)
                if match_difference < closest_match['difference']:
                    closest_match['name'] = solution_figure_name
                    closest_match['difference'] = match_difference

        return int(closest_match['name'])
